
//=========================================================================================================================

#define EEPROM_ESID_SIZE                        32
#define EEPROM_EPASS_SIZE                       64
#define EEPROM_EMON_API_KEY_SIZE                33
#define EEPROM_EMON_SERVER_SIZE                 32
#define EEPROM_EMON_PATH_SIZE                   16
#define EEPROM_EMON_NODE_SIZE                   32
#define EEPROM_MQTT_SERVER_SIZE                 32
#define EEPROM_MQTT_TOPIC_SIZE                  32
#define EEPROM_MQTT_USER_SIZE                   32
#define EEPROM_MQTT_PASS_SIZE                   64
#define EEPROM_EMON_FINGERPRINT_SIZE            60
#define EEPROM_MQTT_FEED_PREFIX_SIZE            10
#define EEPROM_WWW_USER_SIZE                    16
#define EEPROM_WWW_PASS_SIZE                    16
#define EEPROM_CAL_VOLTAGE1_SIZE                 6
#define EEPROM_CAL_VOLTAGE2_SIZE                 6
#define EEPROM_CAL_VOLTAGE3_SIZE                 6
#define EEPROM_CAL_CT1_SIZE						6
#define EEPROM_CAL_CT2_SIZE                     6
#define EEPROM_CAL_CT3_SIZE                     6
#define EEPROM_CAL_FREQ_SIZE                    6
#define EEPROM_CAL_GAIN_SIZE                    6


//Devise Calibration Data
#define EEPROM_PhaA_ActivePowerOffset_SIZE				16
#define EEPROM_PhaA_ReactivePowerOffset_SIZE			16
#define EEPROM_PhaB_ActivePowerOffset_SIZE				16
#define EEPROM_PhaB_ReactivePowerOffset_SIZE			16
#define EEPROM_PhaC_ActivePowerOffset_SIZE				16
#define EEPROM_PhaC_ReactivePowerOffset_SIZE			16
#define EEPROM_PhaA_calibrationgain_SIZE				16
#define EEPROM_PhaA_Phaseangle_SIZE						16
#define EEPROM_PhaB_calibrationgain_SIZE				16
#define EEPROM_PhaB_Phaseangle_SIZE						16
#define EEPROM_PhaC_calibrationgain_SIZE				16
#define EEPROM_PhaC_Phaseangle_SIZE						16
#define EEPROM_CHECKSUM1_SIZE							6

#define EEPROM_PhaA_FundActivePowerOffset_SIZE			16
#define EEPROM_PhaB_FundActivePowerOffset_SIZE			16
#define EEPROM_PhaC_FundActivePowerOffset_SIZE			16
#define EEPROM_PhaA_FundActivePowerGain_SIZE			16
#define EEPROM_PhaB_FundActivePowerGain_SIZE			16
#define EEPROM_PhaC_FundActivePowerGain_SIZE			16
#define EEPROM_CHECKSUM2_SIZE							6

#define EEPROM_PhaA_VoltageRMSGain_SIZE					16
#define EEPROM_PhaA_CurrentRMSGain_SIZE					16
#define EEPROM_PhaA_VoltageRMSOffset_SIZE				16
#define EEPROM_PhaA_CurrentRMSOffset_SIZE				16
#define EEPROM_PhaB_VoltageRMSGain_SIZE					16
#define EEPROM_PhaB_CurrentRMSGain_SIZE					16
#define EEPROM_PhaB_VoltageRMSOffset_SIZE				16
#define EEPROM_PhaB_CurrentRMSOffset_SIZE				16
#define EEPROM_PhaC_VoltageRMSGain_SIZE					16
#define EEPROM_PhaC_CurrentRMSGain_SIZE					16
#define EEPROM_PhaC_VoltageRMSOffset_SIZE				16
#define EEPROM_PhaC_CurrentRMSOffset_SIZE				16
#define EEPROM_Sampled_NlineCurrentRMSGain_SIZE			16
#define EEPROM_Sampled_NlineCurrentRMSOffset_SIZE		16
#define EEPROM_CHECKSUM3_SIZE							6



//Devise Measuring and Energy Data
#define EEPROM_TOTALFWDACTIVEENERGY_SIZE                        16
#define EEPROM_PhaA_FWDACTIVEENERGY_SIZE                        16
#define EEPROM_PhaB_FWDACTIVEENERGY_SIZE                        16
#define EEPROM_PhaC_FWDACTIVEENERGY_SIZE                        16
#define EEPROM_TotalREVACTIVEENERGY_SIZE                        16
#define EEPROM_PhaA_REVACTIVEENERGY_SIZE                        16
#define EEPROM_PhaB_REVACTIVEENERGY_SIZE                        16
#define EEPROM_PhaC_REVACTIVEENERGY_SIZE                        16
#define EEPROM_TotalFWDREACTIVEENERGY_SIZE                      16
#define EEPROM_PhaA_FWDREACTIVEENERGY_SIZE                      16
#define EEPROM_PhaB_FWDREACTIVEENERGY_SIZE                      16
#define EEPROM_PhaC_FWDREACTIVEENERGY_SIZE                      16
#define EEPROM_TotalREVREACTIVEENERGY_SIZE                      16
#define EEPROM_PhaA_REVREACTIVEENERGY_SIZE                      16
#define EEPROM_PhaB_REVREACTIVEENERGY_SIZE                      16
#define EEPROM_PhaC_REVREACTIVEENERGY_SIZE                      16
#define EEPROM_TOTAL_ARITHMETICSUMAPPARENTENERGY_SIZE           16
#define EEPROM_PHAA_APPARENTENERGY_SIZE							16
#define EEPROM_PHAB_APPARENTENERGY_SIZE							16
#define EEPROM_PHAC_APPARENTENERGY_SIZE							16
#define EEPROM_TOTALAPPARENTENERGY_SIZE							16
#define EEPROM_TOTAL_VECTORSUMAPPARENTENERGY_SIZE				16
#define EEPROM_VECTORSUMTOTALAPPARENTPOWER_SIZE					16



//Fundamental / Harmonic Energy Register
#define EEPROM_TOTALFWDACTIVEFUNDENERGY_SIZE                    16
#define EEPROM_PHAA_FWDACTIVEFUNDENERGY_SIZE                    16
#define EEPROM_PHAB_FWDACTIVEFUNDENERGY_SIZE                    16
#define EEPROM_PHAC_FWDACTIVEFUNDENERGY_SIZE                    16
#define EEPROM_TOTALREVACTIVEFUNDENERGY_SIZE                    16
#define EEPROM_PHAA_REVACTIVEFUNDENERGY_SIZE                    16
#define EEPROM_PHAB_REVACTIVEFUNDENERGY_SIZE                    16
#define EEPROM_PHAC_REVACTIVEFUNDENERGY_SIZE                    16
#define EEPROM_TOTALFWDACTIVEHARMONICENERGY_SIZE                16
#define EEPROM_PHAA_FWDACTIVEHARMONICENERGY_SIZE				16       
#define EEPROM_PHAB_FWDACTIVEHARMONICENERGY_SIZE				16 
#define EEPROM_PHAC_FWDACTIVEHARMONICENERGY_SIZE				16 
#define EEPROM_TOTALREVACTIVEHARMONICENERGY_SIZE                16
#define EEPROM_PHAA_REVACTIVEHARMONICENERGY_SIZE                16
#define EEPROM_PHAB_REVACTIVEHARMONICENERGY_SIZE                16
#define EEPROM_PHAC_REVACTIVEHARMONICENERGY_SIZE                16

//======================================================================================================

//Power and Power Factor Registers
#define EEPROM_TOTAL_ALLPHASESUMACTIVEPOWER_SIZE                16
#define EEPROM_PHAA_ACTIVEPOWER_SIZE							16
#define EEPROM_PHAB_ACTIVEPOWER_SIZE							16
#define EEPROM_PHAC_ACTIVEPOWER_SIZE							16
#define EEPROM_TOTAL_ALLPHASESUMREACTIVEPOWER_SIZE              16
#define EEPROM_PHAA_REACTIVEPOWER_SIZE							16
#define EEPROM_PHAB_REACTIVEPOWER_SIZE							16
#define EEPROM_PHAC_REACTIVEPOWER_SIZE							16
#define EEPROM_TOTAL_ARITHMETICSUMAPPARENTPOWER_SIZE			16     
#define EEPROM_PHAA_APPARENTPOWER_SIZE							16
#define EEPROM_PHAB_APPARENTPOWER_SIZE							16
#define EEPROM_PHAC_APPARENTPOWER_SIZE							16
#define EEPROM_TOTALPOWERFACTOR_SIZE							16
#define EEPROM_PHAA_POWERFACTOR_SIZE							16
#define EEPROM_PHAB_POWERFACTOR_SIZE							16
#define EEPROM_PHAC_POWERFACTOR_SIZE							16

#define EEPROM_PMEANTLSB_SIZE									16
#define EEPROM_PMEANALSB_SIZE									16
#define EEPROM_PMEANBLSB_SIZE									16
#define EEPROM_PMEANCLSB_SIZE									16
#define EEPROM_QMEANTLSB_SIZE									16
#define EEPROM_QMEANALSB_SIZE									16
#define EEPROM_QMEANBLSB_SIZE									16
#define EEPROM_QMEANCLSB_SIZE									16
#define EEPROM_SAMEANTLSB_SIZE									16
#define EEPROM_SMEANALSB_SIZE									16
#define EEPROM_SMEANBLSB_SIZE									16
#define EEPROM_SMEANCLSB_SIZE									16




//Fundamental / Harmonic Power and Voltage / Current RMS Registers
#define EEPROM_PMEANTF_SIZE										16
#define EEPROM_PMEANAF_SIZE										16
#define EEPROM_PMEANBF_SIZE										16
#define EEPROM_PMEANCF_SIZE										16
#define EEPROM_PMEANTH_SIZE										16
#define EEPROM_PMEANAH_SIZE										16
#define EEPROM_PMEANBH_SIZE										16
#define EEPROM_PMEANCH_SIZE										16
#define EEPROM_IRMSN1_SIZE										16
#define EEPROM_URMSA_SIZE										16
#define EEPROM_URMSB_SIZE										16
#define EEPROM_URMSC_SIZE										16
#define EEPROM_IRMSN0_SIZE										16
#define EEPROM_IRMSA_SIZE										16
#define EEPROM_IRMSB_SIZE										16
#define EEPROM_IRMSC_SIZE										16
#define EEPROM_PMEANTFLSB_SIZE									16
#define EEPROM_PMEANAFLSB_SIZE									16
#define EEPROM_PMEANBFLSB_SIZE									16
#define EEPROM_PMEANCFLSB_SIZE									16
#define EEPROM_PMEANTHLSB_SIZE									16
#define EEPROM_PMEANAHLSB_SIZE									16
#define EEPROM_PMEANBHLSB_SIZE									16
#define EEPROM_PMEANCHLSB_SIZE									16
#define EEPROM_URMSALSB_SIZE									16
#define EEPROM_URMSBLSB_SIZE									16
#define EEPROM_URMSCLSB_SIZE									16
#define EEPROM_IRMSALSB_SIZE									16
#define EEPROM_IRMSBLSB_SIZE									16
#define EEPROM_IRMSCLSB_SIZE									16
//======================================================================================================

//THD+N, Frequency, Angle and Temperature Registers
#define EEPROM_THDNUA_SIZE										16
#define EEPROM_THDNUB_SIZE										16
#define EEPROM_THDNUC_SIZE										16
#define EEPROM_THDNIA_SIZE										16
#define EEPROM_THDNIB_SIZE										16
#define EEPROM_THDNIC_SIZE										16
#define EEPROM_FREQ_SIZE										16
#define EEPROM_PANGLEA_SIZE										16
#define EEPROM_PANGLEB_SIZE										16
#define EEPROM_PANGLEC_SIZE										16
#define EEPROM_TEMP_SIZE										16
#define EEPROM_UANGLEA_SIZE										16
#define EEPROM_UANGLEB_SIZE										16
#define EEPROM_UANGLEC_SIZE										16


#define EEPROM_TEMPERATURE_SIZE									16
#define EEPROM_TEMPERATURE_F_SIZE								16
#define EEPROM_HUMIDITY_SIZE									16
#define EEPROM_HEATINDEX_TEMP_SIZE								16
#define EEPROM_HEATINDEX_HUM_SIZE								16




#ifdef SOLAR_METER
#define EEPROM_CAL_SVOLTAGE_SIZE  6
#define EEPROM_CAL_SCT1_SIZE      6
#define EEPROM_CAL_SCT2_SIZE      6
#endif
#define EEPROM_SIZE               8192

#define EEPROM_VENDOR_NAME_SIZE                       32
#define EEPROM_PRODUCT_CODE_SIZE                      32
#define EEPROM_REVISION_NUMBER_SIZE                   32
#define EEPROM_METER_NAME_SIZE                        32
#define EEPROM_MODEL_SIZE                             32
#define EEPROM_MANUFACTURER_SIZE                      32
#define EEPROM_SERIAL_NO_SIZE                         32
#define EEPROM_HARDWARE_REV_SIZE                      16
#define EEPROM_FIRMWARE_VER_SIZE                      32
#define EEPROM_MAC_ADD_SIZE							  32
#define EEPROM_NODE_SIZE							  32
#define EEPROM_NODE_ID_SIZE							  32


#define EEPROM_VENDOR_NAME_START         0
#define EEPROM_VENDOR_NAME_END           (EEPROM_VENDOR_NAME_START + EEPROM_VENDOR_NAME_SIZE)
#define EEPROM_PRODUCT_CODEE_START         EEPROM_VENDOR_NAME_END
#define EEPROM_PRODUCT_CODE_END           (EEPROM_PRODUCT_CODEE_START + EEPROM_PRODUCT_CODE_SIZE)
#define EEPROM_REVISION_NUMBER_START         EEPROM_PRODUCT_CODE_END
#define EEPROM_REVISION_NUMBER_END           (EEPROM_REVISION_NUMBER_START + EEPROM_REVISION_NUMBER_SIZE)
#define EEPROM_METER_NAME_START         EEPROM_REVISION_NUMBER_END
#define EEPROM_METER_NAME_END           (EEPROM_METER_NAME_START + EEPROM_METER_NAME_SIZE)
#define EEPROM_MODEL_START         EEPROM_METER_NAME_END
#define EEPROM_MODEL_END           (EEPROM_MODEL_START + EEPROM_MODEL_SIZE)
#define EEPROM_MANUFACTURER_START         EEPROM_MODEL_END
#define EEPROM_MANUFACTURER_END           (EEPROM_MANUFACTURER_START + EEPROM_MANUFACTURER_SIZE)
#define EEPROM_SERIAL_NO_START         EEPROM_MANUFACTURER_END
#define EEPROM_SERIAL_NO_END           (EEPROM_SERIAL_NO_START + EEPROM_SERIAL_NO_SIZE)
#define EEPROM_HARDWARE_REV_START         EEPROM_SERIAL_NO_END
#define EEPROM_HARDWARE_REV_END           (EEPROM_HARDWARE_REV_START + EEPROM_HARDWARE_REV_SIZE)
#define EEPROM_FIRMWARE_VER_START         EEPROM_HARDWARE_REV_END
#define EEPROM_FIRMWARE_VER_END           (EEPROM_FIRMWARE_VER_START + EEPROM_FIRMWARE_VER_SIZE)
#define EEPROM_MAC_ADD_START         EEPROM_FIRMWARE_VER_END
#define EEPROM_MAC_ADD_END           (EEPROM_MAC_ADD_START + EEPROM_MAC_ADD_SIZE)
#define EEPROM_NODE_START         EEPROM_MAC_ADD_END
#define EEPROM_NODE_END           (EEPROM_NODE_START + EEPROM_NODE_SIZE)
#define EEPROM_NODE_ID_START         EEPROM_NODE_END
#define EEPROM_NODE_ID_END           (EEPROM_NODE_ID_START + EEPROM_NODE_ID_SIZE)

#define EEPROM_ESID_START         (EEPROM_NODE_ID_END+5)
#define EEPROM_ESID_END           (EEPROM_ESID_START + EEPROM_ESID_SIZE)
#define EEPROM_EPASS_START        EEPROM_ESID_END
#define EEPROM_EPASS_END          (EEPROM_EPASS_START + EEPROM_EPASS_SIZE)
#define EEPROM_EMON_API_KEY_START EEPROM_EPASS_END
#define EEPROM_EMON_API_KEY_END   (EEPROM_EMON_API_KEY_START + EEPROM_EMON_API_KEY_SIZE)
#define EEPROM_EMON_SERVER_START  EEPROM_EMON_API_KEY_END
#define EEPROM_EMON_SERVER_END    (EEPROM_EMON_SERVER_START + EEPROM_EMON_SERVER_SIZE)
#define EEPROM_EMON_NODE_START    EEPROM_EMON_SERVER_END
#define EEPROM_EMON_NODE_END      (EEPROM_EMON_NODE_START + EEPROM_EMON_NODE_SIZE)
#define EEPROM_MQTT_SERVER_START  EEPROM_EMON_NODE_END
#define EEPROM_MQTT_SERVER_END    (EEPROM_MQTT_SERVER_START + EEPROM_MQTT_SERVER_SIZE)
#define EEPROM_MQTT_TOPIC_START   EEPROM_MQTT_SERVER_END
#define EEPROM_MQTT_TOPIC_END     (EEPROM_MQTT_TOPIC_START + EEPROM_MQTT_TOPIC_SIZE)
#define EEPROM_MQTT_USER_START    EEPROM_MQTT_TOPIC_END
#define EEPROM_MQTT_USER_END      (EEPROM_MQTT_USER_START + EEPROM_MQTT_USER_SIZE)
#define EEPROM_MQTT_PASS_START    EEPROM_MQTT_USER_END
#define EEPROM_MQTT_PASS_END      (EEPROM_MQTT_PASS_START + EEPROM_MQTT_PASS_SIZE)
#define EEPROM_EMON_FINGERPRINT_START  EEPROM_MQTT_PASS_END
#define EEPROM_EMON_FINGERPRINT_END    (EEPROM_EMON_FINGERPRINT_START + EEPROM_EMON_FINGERPRINT_SIZE)
#define EEPROM_MQTT_FEED_PREFIX_START  EEPROM_EMON_FINGERPRINT_END
#define EEPROM_MQTT_FEED_PREFIX_END    (EEPROM_MQTT_FEED_PREFIX_START + EEPROM_MQTT_FEED_PREFIX_SIZE)
#define EEPROM_WWW_USER_START     EEPROM_MQTT_FEED_PREFIX_END
#define EEPROM_WWW_USER_END       (EEPROM_WWW_USER_START + EEPROM_WWW_USER_SIZE)
#define EEPROM_WWW_PASS_START     EEPROM_WWW_USER_END
#define EEPROM_WWW_PASS_END       (EEPROM_WWW_PASS_START + EEPROM_WWW_PASS_SIZE)
#define EEPROM_EMON_PATH_START    EEPROM_WWW_PASS_END
#define EEPROM_EMON_PATH_END      (EEPROM_EMON_PATH_START + EEPROM_EMON_PATH_SIZE)

#define EEPROM_CAL_VOLTAGE1_START  EEPROM_EMON_PATH_END
#define EEPROM_CAL_VOLTAGE1_END    (EEPROM_CAL_VOLTAGE1_START + EEPROM_CAL_VOLTAGE1_SIZE)
#define EEPROM_CAL_VOLTAGE2_START  EEPROM_CAL_VOLTAGE1_END
#define EEPROM_CAL_VOLTAGE2_END    (EEPROM_CAL_VOLTAGE2_START + EEPROM_CAL_VOLTAGE2_SIZE)
#define EEPROM_CAL_VOLTAGE3_START  EEPROM_CAL_VOLTAGE2_END
#define EEPROM_CAL_VOLTAGE3_END    (EEPROM_CAL_VOLTAGE3_START + EEPROM_CAL_VOLTAGE3_SIZE)
#define EEPROM_CAL_CT1_START   EEPROM_CAL_VOLTAGE3_END
#define EEPROM_CAL_CT1_END     (EEPROM_CAL_CT1_START + EEPROM_CAL_CT1_SIZE)
#define EEPROM_CAL_CT2_START    EEPROM_CAL_CT1_END
#define EEPROM_CAL_CT2_END      (EEPROM_CAL_CT2_START + EEPROM_CAL_CT2_SIZE)
#define EEPROM_CAL_CT3_START    EEPROM_CAL_CT2_END
#define EEPROM_CAL_CT3_END      (EEPROM_CAL_CT3_START + EEPROM_CAL_CT3_SIZE)
#define EEPROM_CAL_FREQ_START    EEPROM_CAL_CT3_END
#define EEPROM_CAL_FREQ_END      (EEPROM_CAL_FREQ_START + EEPROM_CAL_FREQ_SIZE)
#define EEPROM_CAL_GAIN_START    EEPROM_CAL_FREQ_END
#define EEPROM_CAL_GAIN_END      (EEPROM_CAL_GAIN_START + EEPROM_CAL_GAIN_SIZE)

//Calibration Registers - EEPROM Locations
#define EEPROM_PHAA_ACTIVEPOWEROFFSET_START    EEPROM_CAL_GAIN_END
#define EEPROM_PHAA_ACTIVEPOWEROFFSET_END      (EEPROM_PHAA_ACTIVEPOWEROFFSET_START + EEPROM_PhaA_ActivePowerOffset_SIZE)
#define EEPROM_PHAA_REACTIVEPOWEROFFSET_START    EEPROM_PHAA_ACTIVEPOWEROFFSET_END
#define EEPROM_PHAA_REACTIVEPOWEROFFSET_END      (EEPROM_PHAA_REACTIVEPOWEROFFSET_START + EEPROM_PhaA_ReactivePowerOffset_SIZE)
#define EEPROM_PHAB_ACTIVEPOWEROFFSET_START    EEPROM_PHAA_REACTIVEPOWEROFFSET_END
#define EEPROM_PHAB_ACTIVEPOWEROFFSET_END      (EEPROM_PHAB_ACTIVEPOWEROFFSET_START + EEPROM_PhaB_ActivePowerOffset_SIZE)
#define EEPROM_PHAB_REACTIVEPOWEROFFSET_START    EEPROM_PHAB_ACTIVEPOWEROFFSET_END
#define EEPROM_PHAB_REACTIVEPOWEROFFSET_END      (EEPROM_PHAB_REACTIVEPOWEROFFSET_START + EEPROM_PhaB_ReactivePowerOffset_SIZE)
#define EEPROM_PHAC_ACTIVEPOWEROFFSET_START    EEPROM_PHAB_REACTIVEPOWEROFFSET_END
#define EEPROM_PHAC_ACTIVEPOWEROFFSET_END      (EEPROM_PHAC_ACTIVEPOWEROFFSET_START + EEPROM_PhaC_ActivePowerOffset_SIZE)
#define EEPROM_PHAC_REACTIVEPOWEROFFSET_START    EEPROM_PHAC_ACTIVEPOWEROFFSET_END
#define EEPROM_PHAC_REACTIVEPOWEROFFSET_END      (EEPROM_PHAC_REACTIVEPOWEROFFSET_START + EEPROM_PhaC_ReactivePowerOffset_SIZE)
#define EEPROM_PHAA_CALIBRATIONGAIN_START    EEPROM_PHAC_REACTIVEPOWEROFFSET_END
#define EEPROM_PHAA_CALIBRATIONGAIN_END      (EEPROM_PHAA_CALIBRATIONGAIN_START + EEPROM_PhaA_calibrationgain_SIZE)
#define EEPROM_PHAA_PHASEANGLE_START    EEPROM_PHAA_CALIBRATIONGAIN_END
#define EEPROM_PHAA_PHAA_PHASEANGLE_END      (EEPROM_PHAA_PHASEANGLE_START + EEPROM_PhaA_Phaseangle_SIZE)
#define EEPROM_PHAB_CALIBRATIONGAIN_START    EEPROM_PHAA_PHAA_PHASEANGLE_END
#define EEPROM_PHAB_CALIBRATIONGAIN_END      (EEPROM_PHAB_CALIBRATIONGAIN_START + EEPROM_PhaB_calibrationgain_SIZE)
#define EEPROM_PHAB_PHASEANGLE_START    EEPROM_PHAB_CALIBRATIONGAIN_END
#define EEPROM_PHAB_PHAA_PHASEANGLE_END      (EEPROM_PHAB_PHASEANGLE_START + EEPROM_PhaB_Phaseangle_SIZE)
#define EEPROM_PHAC_CALIBRATIONGAIN_START    EEPROM_PHAB_PHAA_PHASEANGLE_END
#define EEPROM_PHAC_CALIBRATIONGAIN_END      (EEPROM_PHAC_CALIBRATIONGAIN_START + EEPROM_PhaC_calibrationgain_SIZE)
#define EEPROM_PHAC_PHASEANGLE_START    EEPROM_PHAC_CALIBRATIONGAIN_END
#define EEPROM_PHAC_PHAA_PHASEANGLE_END      (EEPROM_PHAC_PHASEANGLE_START + EEPROM_PhaC_Phaseangle_SIZE)
#define EEPROM_CHECKSUM1_START    EEPROM_PHAC_PHAA_PHASEANGLE_END
#define EEPROM_CHECKSUM1_END      (EEPROM_CHECKSUM1_START + EEPROM_CHECKSUM1_SIZE)

//Fundamental/ Harmonic Energy Calibration registers - EEPROM Locations
#define EEPROM_PHAA_FUNDACTIVEPOWEROFFSET_START    EEPROM_CHECKSUM1_END
#define EEPROM_PHAA_FUNDACTIVEPOWEROFFSET_END      (EEPROM_PHAA_FUNDACTIVEPOWEROFFSET_START + EEPROM_PhaA_FundActivePowerOffset_SIZE)
#define EEPROM_PHAB_FUNDACTIVEPOWEROFFSET_START    EEPROM_PHAA_FUNDACTIVEPOWEROFFSET_END
#define EEPROM_PHAB_FUNDACTIVEPOWEROFFSET_END      (EEPROM_PHAB_FUNDACTIVEPOWEROFFSET_START + EEPROM_PhaB_FundActivePowerOffset_SIZE)
#define EEPROM_PHAC_FUNDACTIVEPOWEROFFSET_START    EEPROM_PHAB_FUNDACTIVEPOWEROFFSET_END
#define EEPROM_PHAC_FUNDACTIVEPOWEROFFSET_END      (EEPROM_PHAC_FUNDACTIVEPOWEROFFSET_START + EEPROM_PhaC_FundActivePowerOffset_SIZE)
#define EEPROM_PHAA_FUNDACTIVEPOWERGAIN_START    EEPROM_PHAC_FUNDACTIVEPOWEROFFSET_END
#define EEPROM_PHAA_FUNDACTIVEPOWERGAIN_END      (EEPROM_PHAA_FUNDACTIVEPOWERGAIN_START + EEPROM_PhaA_FundActivePowerGain_SIZE)
#define EEPROM_PHAB_FUNDACTIVEPOWERGAIN_START    EEPROM_PHAA_FUNDACTIVEPOWERGAIN_END
#define EEPROM_PHAB_FUNDACTIVEPOWERGAIN_END      (EEPROM_PHAB_FUNDACTIVEPOWERGAIN_START + EEPROM_PhaB_FundActivePowerGain_SIZE)
#define EEPROM_PHAC_FUNDACTIVEPOWERGAIN_START    EEPROM_PHAB_FUNDACTIVEPOWERGAIN_END
#define EEPROM_PHAC_FUNDACTIVEPOWERGAIN_END      (EEPROM_PHAC_FUNDACTIVEPOWERGAIN_START + EEPROM_PhaC_FundActivePowerGain_SIZE)
#define EEPROM_CHECKSUM2_START    EEPROM_PHAC_FUNDACTIVEPOWERGAIN_END
#define EEPROM_CHECKSUM2_END      (EEPROM_CHECKSUM2_START + EEPROM_CHECKSUM2_SIZE)


//Measurement Calibration - EEPROM Locations
#define EEPROM_PHAA_VOLTAGERMSGAIN_START    EEPROM_CHECKSUM2_END
#define EEPROM_PHAA_VOLTAGERMSGAIN_END      (EEPROM_PHAA_VOLTAGERMSGAIN_START + EEPROM_PhaA_VoltageRMSGain_SIZE)
#define EEPROM_PHAA_CURRENTRMSGAIN_START    EEPROM_PHAA_VOLTAGERMSGAIN_END
#define EEPROM_PHAA_CURRENTRMSGAIN_END      (EEPROM_PHAA_CURRENTRMSGAIN_START + EEPROM_PhaA_CurrentRMSGain_SIZE)
#define EEPROM_PHAA_VOLTAGERMSOFFSET_START    EEPROM_PHAA_CURRENTRMSGAIN_END
#define EEPROM_PHAA_VOLTAGERMSOFFSET_END      (EEPROM_PHAA_VOLTAGERMSOFFSET_START + EEPROM_PhaA_VoltageRMSOffset_SIZE)
#define EEPROM_PHAA_CURRENTRMSOFFSET_START    EEPROM_PHAA_VOLTAGERMSOFFSET_END
#define EEPROM_PHAA_CURRENTRMSOFFSET_END      (EEPROM_PHAA_CURRENTRMSOFFSET_START + EEPROM_PhaA_CurrentRMSOffset_SIZE)
#define EEPROM_PHAB_VOLTAGERMSGAIN_START    EEPROM_PHAA_CURRENTRMSOFFSET_END
#define EEPROM_PHAB_VOLTAGERMSGAIN_END      (EEPROM_PHAB_VOLTAGERMSGAIN_START + EEPROM_PhaB_VoltageRMSGain_SIZE)
#define EEPROM_PHAB_CURRENTRMSGAIN_START    EEPROM_PHAB_VOLTAGERMSGAIN_END
#define EEPROM_PHAB_CURRENTRMSGAIN_END      (EEPROM_PHAB_CURRENTRMSGAIN_START + EEPROM_PhaB_CurrentRMSGain_SIZE)
#define EEPROM_PHAB_VOLTAGERMSOFFSET_START    EEPROM_PHAB_CURRENTRMSGAIN_END
#define EEPROM_PHAB_VOLTAGERMSOFFSET_END      (EEPROM_PHAB_VOLTAGERMSOFFSET_START + EEPROM_PhaB_VoltageRMSOffset_SIZE)
#define EEPROM_PHAB_CURRENTRMSOFFSET_START    EEPROM_PHAB_VOLTAGERMSOFFSET_END
#define EEPROM_PHAB_CURRENTRMSOFFSET_END      (EEPROM_PHAB_CURRENTRMSOFFSET_START + EEPROM_PhaB_CurrentRMSOffset_SIZE)
#define EEPROM_PHAC_VOLTAGERMSGAIN_START    EEPROM_PHAB_CURRENTRMSOFFSET_END
#define EEPROM_PHAC_VOLTAGERMSGAIN_END      (EEPROM_PHAC_VOLTAGERMSGAIN_START + EEPROM_PhaC_VoltageRMSGain_SIZE)
#define EEPROM_PHAC_CURRENTRMSGAIN_START    EEPROM_PHAC_VOLTAGERMSGAIN_END
#define EEPROM_PHAC_CURRENTRMSGAIN_END      (EEPROM_PHAC_CURRENTRMSGAIN_START + EEPROM_PhaC_CurrentRMSGain_SIZE)
#define EEPROM_PHAC_VOLTAGERMSOFFSET_START    EEPROM_PHAC_CURRENTRMSGAIN_END
#define EEPROM_PHAC_VOLTAGERMSOFFSET_END      (EEPROM_PHAC_VOLTAGERMSOFFSET_START + EEPROM_PhaC_VoltageRMSOffset_SIZE)
#define EEPROM_PHAC_CURRENTRMSOFFSET_START    EEPROM_PHAC_VOLTAGERMSOFFSET_END
#define EEPROM_PHAC_CURRENTRMSOFFSET_END      (EEPROM_PHAC_CURRENTRMSOFFSET_START + EEPROM_PhaC_CurrentRMSOffset_SIZE)
#define EEPROM_SAMPLED_NLINECURRENTRMSGAIN_START    EEPROM_PHAC_CURRENTRMSOFFSET_END
#define EEPROM_SAMPLED_NLINECURRENTRMSGAIN_END      (EEPROM_SAMPLED_NLINECURRENTRMSGAIN_START + EEPROM_Sampled_NlineCurrentRMSGain_SIZE)
#define EEPROM_SAMPLED_NLINECURRENTRMSOFFSET_START    EEPROM_SAMPLED_NLINECURRENTRMSGAIN_END
#define EEPROM_SAMPLED_NLINECURRENTRMSOFFSET_END      (EEPROM_SAMPLED_NLINECURRENTRMSOFFSET_START + EEPROM_Sampled_NlineCurrentRMSOffset_SIZE)
#define EEPROM_CHECKSUM3_START    EEPROM_SAMPLED_NLINECURRENTRMSOFFSET_END
#define EEPROM_CHECKSUM3_END      (EEPROM_CHECKSUM3_START + EEPROM_CHECKSUM3_SIZE)


#define EEPROM_TOTALFWDACTIVEENERGY_START    EEPROM_CHECKSUM3_END
#define EEPROM_TOTALFWDACTIVEENERGY_END      (EEPROM_TOTALFWDACTIVEENERGY_START + EEPROM_TOTALFWDACTIVEENERGY_SIZE)
#define EEPROM_PHAA_FWDACTIVEENERGY_START    EEPROM_TOTALFWDACTIVEENERGY_END
#define EEPROM_PHAA_FWDACTIVEENERGY_END      (EEPROM_PHAA_FWDACTIVEENERGY_START + EEPROM_PhaA_FWDACTIVEENERGY_SIZE)
#define EEPROM_PHAB_FWDACTIVEENERGY_START    EEPROM_PHAA_FWDACTIVEENERGY_END
#define EEPROM_PHAB_FWDACTIVEENERGY_END      (EEPROM_PHAB_FWDACTIVEENERGY_START + EEPROM_PhaB_FWDACTIVEENERGY_SIZE)
#define EEPROM_PHAC_FWDACTIVEENERGY_START    EEPROM_PHAB_FWDACTIVEENERGY_END
#define EEPROM_PHAC_FWDACTIVEENERGY_END      (EEPROM_PHAC_FWDACTIVEENERGY_START + EEPROM_PhaC_FWDACTIVEENERGY_SIZE)
#define EEPROM_TOTALREVACTIVEENERGY_START    EEPROM_PHAC_FWDACTIVEENERGY_END
#define EEPROM_TOTALREVACTIVEENERGY_END      (EEPROM_TOTALREVACTIVEENERGY_START + EEPROM_TotalREVACTIVEENERGY_SIZE)
#define EEPROM_PHAA_REVACTIVEENERGY_START    EEPROM_TOTALREVACTIVEENERGY_END
#define EEPROM_PHAA_REVACTIVEENERGY_END      (EEPROM_PHAA_REVACTIVEENERGY_START + EEPROM_PhaA_REVACTIVEENERGY_SIZE)
#define EEPROM_PHAB_REVACTIVEENERGY_START    EEPROM_PHAA_REVACTIVEENERGY_END
#define EEPROM_PHAB_REVACTIVEENERGY_END      (EEPROM_PHAB_REVACTIVEENERGY_START + EEPROM_PhaB_REVACTIVEENERGY_SIZE)
#define EEPROM_PHAC_REVACTIVEENERGY_START    EEPROM_PHAB_REVACTIVEENERGY_END
#define EEPROM_PHAC_REVACTIVEENERGY_END      (EEPROM_PHAC_REVACTIVEENERGY_START + EEPROM_PhaB_REVACTIVEENERGY_SIZE)
#define EEPROM_TOTALFWDREACTIVEENERGY_START    EEPROM_PHAC_REVACTIVEENERGY_END
#define EEPROM_TOTALFWDREACTIVEENERGY_END      (EEPROM_TOTALFWDREACTIVEENERGY_START + EEPROM_TotalFWDREACTIVEENERGY_SIZE)
#define EEPROM_PHAA_FWDREACTIVEENERGY_START    EEPROM_TOTALFWDREACTIVEENERGY_END
#define EEPROM_PHAA_FWDREACTIVEENERGY_END      (EEPROM_PHAA_FWDREACTIVEENERGY_START + EEPROM_PhaA_FWDREACTIVEENERGY_SIZE)
#define EEPROM_PHAB_FWDREACTIVEENERGY_START    EEPROM_PHAA_FWDREACTIVEENERGY_END
#define EEPROM_PHAB_FWDREACTIVEENERGY_END      (EEPROM_PHAB_FWDREACTIVEENERGY_START + EEPROM_PhaB_FWDREACTIVEENERGY_SIZE)
#define EEPROM_PHAC_FWDREACTIVEENERGY_START    EEPROM_PHAB_FWDREACTIVEENERGY_END
#define EEPROM_PHAC_FWDREACTIVEENERGY_END      (EEPROM_PHAC_FWDREACTIVEENERGY_START + EEPROM_PhaC_FWDREACTIVEENERGY_SIZE)
#define EEPROM_TOTALREVREACTIVEENERGY_START    EEPROM_PHAC_FWDREACTIVEENERGY_END
#define EEPROM_TOTALREVREACTIVEENERGY_END      (EEPROM_TOTALREVREACTIVEENERGY_START + EEPROM_TotalREVREACTIVEENERGY_SIZE)
#define EEPROM_PHAA_REVREACTIVEENERGY_START    EEPROM_TOTALREVREACTIVEENERGY_END
#define EEPROM_PHAA_REVREACTIVEENERGY_END      (EEPROM_PHAA_REVREACTIVEENERGY_START + EEPROM_PhaA_REVREACTIVEENERGY_SIZE)
#define EEPROM_PHAB_REVREACTIVEENERGY_START    EEPROM_PHAA_REVREACTIVEENERGY_END
#define EEPROM_PHAB_REVREACTIVEENERGY_END      (EEPROM_PHAB_REVREACTIVEENERGY_START + EEPROM_PhaB_REVREACTIVEENERGY_SIZE)
#define EEPROM_PHAC_REVREACTIVEENERGY_START    EEPROM_PHAB_REVREACTIVEENERGY_END
#define EEPROM_PHAC_REVREACTIVEENERGY_END      (EEPROM_PHAC_REVREACTIVEENERGY_START + EEPROM_PhaB_REVREACTIVEENERGY_SIZE)
#define EEPROM_TOTAL_ARITHMETICSUMAPPARENTENERGY_START    EEPROM_PHAC_REVREACTIVEENERGY_END
#define EEPROM_TOTAL_ARITHMETICSUMAPPARENTENERGY_END      (EEPROM_TOTAL_ARITHMETICSUMAPPARENTENERGY_START + EEPROM_TOTAL_ARITHMETICSUMAPPARENTENERGY_SIZE)
#define EEPROM_PHAA_APPARENTENERGY_START    EEPROM_TOTAL_ARITHMETICSUMAPPARENTENERGY_END
#define EEPROM_PHAA_APPARENTENERGY_END      (EEPROM_PHAA_APPARENTENERGY_START + EEPROM_PHAA_APPARENTENERGY_SIZE)
#define EEPROM_PHAB_APPARENTENERGY_START    EEPROM_PHAA_APPARENTENERGY_END
#define EEPROM_PHAB_APPARENTENERGY_END      (EEPROM_PHAB_APPARENTENERGY_START + EEPROM_PHAB_APPARENTENERGY_SIZE)
#define EEPROM_PHAC_APPARENTENERGY_START    EEPROM_PHAB_APPARENTENERGY_END
#define EEPROM_PHAC_APPARENTENERGY_END      (EEPROM_PHAC_APPARENTENERGY_START + EEPROM_PHAC_APPARENTENERGY_SIZE)
#define EEPROM_TOTALAPPARENTENERGY_START    EEPROM_PHAC_APPARENTENERGY_END
#define EEPROM_TOTALAPPARENTENERGY_END      (EEPROM_TOTALAPPARENTENERGY_START + EEPROM_TOTALAPPARENTENERGY_SIZE)
#define EEPROM_TOTAL_VECTORSUMAPPARENTENERGY_START    EEPROM_TOTALAPPARENTENERGY_END
#define EEPROM_TOTAL_VECTORSUMAPPARENTENERGY_END      (EEPROM_TOTAL_VECTORSUMAPPARENTENERGY_START + EEPROM_TOTAL_VECTORSUMAPPARENTENERGY_SIZE)
#define EEPROM_VECTORSUMTOTALAPPARENTPOWER_START    EEPROM_TOTAL_VECTORSUMAPPARENTENERGY_END
#define EEPROM_VECTORSUMTOTALAPPARENTPOWER_END      (EEPROM_VECTORSUMTOTALAPPARENTPOWER_START + EEPROM_VECTORSUMTOTALAPPARENTPOWER_SIZE) 

//============================================================================================

#define EEPROM_TOTALFWDACTIVEFUNDENERGY_START    EEPROM_VECTORSUMTOTALAPPARENTPOWER_END
#define EEPROM_TOTALFWDACTIVEFUNDENERGY_END      (EEPROM_TOTALFWDACTIVEFUNDENERGY_START + EEPROM_TOTALFWDACTIVEFUNDENERGY_SIZE) 
#define EEPROM_PHAA_FWDACTIVEFUNDENERGY_START    EEPROM_TOTALFWDACTIVEFUNDENERGY_END
#define EEPROM_PHAA_FWDACTIVEFUNDENERGY_END      (EEPROM_PHAA_FWDACTIVEFUNDENERGY_START + EEPROM_PHAA_FWDACTIVEFUNDENERGY_SIZE)
#define EEPROM_PHAB_FWDACTIVEFUNDENERGY_START    EEPROM_PHAA_FWDACTIVEFUNDENERGY_END
#define EEPROM_PHAB_FWDACTIVEFUNDENERGY_END      (EEPROM_PHAB_FWDACTIVEFUNDENERGY_START + EEPROM_PHAB_FWDACTIVEFUNDENERGY_SIZE)
#define EEPROM_PHAC_FWDACTIVEFUNDENERGY_START    EEPROM_PHAB_FWDACTIVEFUNDENERGY_END
#define EEPROM_PHAC_FWDACTIVEFUNDENERGY_END      (EEPROM_PHAC_FWDACTIVEFUNDENERGY_START + EEPROM_PHAC_FWDACTIVEFUNDENERGY_SIZE)
#define EEPROM_TOTALREVACTIVEFUNDENERGY_START    EEPROM_PHAC_FWDACTIVEFUNDENERGY_END
#define EEPROM_TOTALREVACTIVEFUNDENERGY_END      (EEPROM_TOTALREVACTIVEFUNDENERGY_START + EEPROM_TOTALREVACTIVEFUNDENERGY_SIZE)
#define EEPROM_PHAA_REVACTIVEFUNDENERGY_START    EEPROM_TOTALREVACTIVEFUNDENERGY_END
#define EEPROM_PHAA_REVACTIVEFUNDENERGY_END      (EEPROM_PHAA_REVACTIVEFUNDENERGY_START + EEPROM_PHAA_REVACTIVEFUNDENERGY_SIZE)
#define EEPROM_PHAB_REVACTIVEFUNDENERGY_START    EEPROM_PHAA_REVACTIVEFUNDENERGY_END
#define EEPROM_PHAB_REVACTIVEFUNDENERGY_END      (EEPROM_PHAB_REVACTIVEFUNDENERGY_START + EEPROM_PHAB_REVACTIVEFUNDENERGY_SIZE)
#define EEPROM_PHAC_REVACTIVEFUNDENERGY_START    EEPROM_PHAB_REVACTIVEFUNDENERGY_END
#define EEPROM_PHAC_REVACTIVEFUNDENERGY_END      (EEPROM_PHAC_REVACTIVEFUNDENERGY_START + EEPROM_PHAC_REVACTIVEFUNDENERGY_SIZE)
#define EEPROM_TOTALFWDACTIVEHARMONICENERGY_START    EEPROM_PHAC_REVACTIVEFUNDENERGY_END
#define EEPROM_TOTALFWDACTIVEHARMONICENERGY_END      (EEPROM_TOTALFWDACTIVEHARMONICENERGY_START + EEPROM_TOTALFWDACTIVEHARMONICENERGY_SIZE)
#define EEPROM_PHAA_FWDACTIVEHARMONICENERGY_START    EEPROM_TOTALFWDACTIVEHARMONICENERGY_END
#define EEPROM_PHAA_FWDACTIVEHARMONICENERGY_END      (EEPROM_PHAA_FWDACTIVEHARMONICENERGY_START + EEPROM_PHAA_FWDACTIVEHARMONICENERGY_SIZE )
#define EEPROM_PHAB_FWDACTIVEHARMONICENERGY_START    EEPROM_PHAA_FWDACTIVEHARMONICENERGY_END
#define EEPROM_PHAB_FWDACTIVEHARMONICENERGY_END      (EEPROM_PHAB_FWDACTIVEHARMONICENERGY_START + EEPROM_PHAB_FWDACTIVEHARMONICENERGY_SIZE )
#define EEPROM_PHAC_FWDACTIVEHARMONICENERGY_START    EEPROM_PHAB_FWDACTIVEHARMONICENERGY_END
#define EEPROM_PHAC_FWDACTIVEHARMONICENERGY_END      (EEPROM_PHAC_FWDACTIVEHARMONICENERGY_START + EEPROM_PHAC_FWDACTIVEHARMONICENERGY_SIZE )
#define EEPROM_TOTALREVACTIVEHARMONICENERGY_START    EEPROM_PHAC_FWDACTIVEHARMONICENERGY_END
#define EEPROM_TOTALREVACTIVEHARMONICENERGYY_END      (EEPROM_TOTALREVACTIVEHARMONICENERGY_START + EEPROM_TOTALREVACTIVEHARMONICENERGY_SIZE )
#define EEPROM_PHAA_REVACTIVEHARMONICENERGY_START    EEPROM_TOTALREVACTIVEHARMONICENERGYY_END
#define EEPROM_PHAA_REVACTIVEHARMONICENERGY_END      (EEPROM_PHAA_REVACTIVEHARMONICENERGY_START + EEPROM_PHAA_REVACTIVEHARMONICENERGY_SIZE) 
#define EEPROM_PHAB_REVACTIVEHARMONICENERGY_START    EEPROM_PHAA_REVACTIVEHARMONICENERGY_END
#define EEPROM_PHAB_REVACTIVEHARMONICENERGY_END      (EEPROM_PHAB_REVACTIVEHARMONICENERGY_START + EEPROM_PHAB_REVACTIVEHARMONICENERGY_SIZE) 
#define EEPROM_PHAC_REVACTIVEHARMONICENERGY_START    EEPROM_PHAB_REVACTIVEHARMONICENERGY_END
#define EEPROM_PHAC_REVACTIVEHARMONICENERGY_END      (EEPROM_PHAC_REVACTIVEHARMONICENERGY_START + EEPROM_PHAC_REVACTIVEHARMONICENERGY_SIZE) 

//============================================================================================


#define EEPROM_TOTAL_ALLPHASESUMACTIVEPOWER_START    EEPROM_PHAC_REVACTIVEHARMONICENERGY_END
#define EEPROM_TOTAL_ALLPHASESUMACTIVEPOWER_END      (EEPROM_TOTAL_ALLPHASESUMACTIVEPOWER_START + EEPROM_TOTAL_ALLPHASESUMACTIVEPOWER_SIZE)
#define EEPROM_EEPROM_PHAA_ACTIVEPOWER_START    EEPROM_TOTAL_ALLPHASESUMACTIVEPOWER_END
#define EEPROM_EEPROM_PHAA_ACTIVEPOWER_END      (EEPROM_EEPROM_PHAA_ACTIVEPOWER_START + EEPROM_PHAA_ACTIVEPOWER_SIZE)
#define EEPROM_EEPROM_PHAB_ACTIVEPOWER_START    EEPROM_EEPROM_PHAA_ACTIVEPOWER_END
#define EEPROM_EEPROM_PHAB_ACTIVEPOWER_END      (EEPROM_EEPROM_PHAB_ACTIVEPOWER_START + EEPROM_PHAB_ACTIVEPOWER_SIZE)
#define EEPROM_EEPROM_PHAC_ACTIVEPOWER_START    EEPROM_EEPROM_PHAB_ACTIVEPOWER_END
#define EEPROM_EEPROM_PHAC_ACTIVEPOWER_END      (EEPROM_EEPROM_PHAC_ACTIVEPOWER_START + EEPROM_PHAC_ACTIVEPOWER_SIZE)
#define EEPROM_TOTAL_ALLPHASESUMREACTIVEPOWER_START    EEPROM_EEPROM_PHAC_ACTIVEPOWER_END
#define EEPROM_TOTAL_ALLPHASESUMREACTIVEPOWER_END      (EEPROM_TOTAL_ALLPHASESUMREACTIVEPOWER_START + EEPROM_TOTAL_ALLPHASESUMREACTIVEPOWER_SIZE)
#define EEPROM_PHAA_REACTIVEPOWER_START    EEPROM_TOTAL_ALLPHASESUMREACTIVEPOWER_END
#define EEPROM_PHAA_REACTIVEPOWER_END      (EEPROM_PHAA_REACTIVEPOWER_START + EEPROM_PHAA_REACTIVEPOWER_SIZE)
#define EEPROM_PHAB_REACTIVEPOWER_START    EEPROM_PHAA_REACTIVEPOWER_END
#define EEPROM_PHAB_REACTIVEPOWER_END      (EEPROM_PHAB_REACTIVEPOWER_START + EEPROM_PHAB_REACTIVEPOWER_SIZE)
#define EEPROM_PHAC_REACTIVEPOWER_START    EEPROM_PHAB_REACTIVEPOWER_END
#define EEPROM_PHAC_REACTIVEPOWER_END      (EEPROM_PHAC_REACTIVEPOWER_START + EEPROM_PHAC_REACTIVEPOWER_SIZE)
#define EEPROM_TOTAL_ARITHMETICSUMAPPARENTPOWER_START    EEPROM_PHAC_REACTIVEPOWER_END
#define EEPROM_TOTAL_ARITHMETICSUMAPPARENTPOWER_END      (EEPROM_TOTAL_ARITHMETICSUMAPPARENTPOWER_START + EEPROM_TOTAL_ARITHMETICSUMAPPARENTPOWER_SIZE)
#define EEPROM_PHAA_APPARENTPOWER_START    EEPROM_TOTAL_ARITHMETICSUMAPPARENTPOWER_END
#define EEPROM_PHAA_APPARENTPOWER_END      (EEPROM_PHAA_APPARENTPOWER_START + EEPROM_PHAA_APPARENTPOWER_SIZE)
#define EEPROM_PHAB_APPARENTPOWER_START    EEPROM_PHAA_APPARENTPOWER_END
#define EEPROM_PHAB_APPARENTPOWER_END      (EEPROM_PHAB_APPARENTPOWER_START + EEPROM_PHAB_APPARENTPOWER_SIZE)
#define EEPROM_PHAC_APPARENTPOWER_START    EEPROM_PHAB_APPARENTPOWER_END
#define EEPROM_PHAC_APPARENTPOWER_END      (EEPROM_PHAC_APPARENTPOWER_START + EEPROM_PHAC_APPARENTPOWER_SIZE)
#define EEPROM_TOTALPOWERFACTOR_START    EEPROM_PHAC_APPARENTPOWER_END
#define EEPROM_TOTALPOWERFACTOR_END      (EEPROM_TOTALPOWERFACTOR_START + EEPROM_TOTALPOWERFACTOR_SIZE)
#define EEPROM_PHAA_POWERFACTOR_START    EEPROM_TOTALPOWERFACTOR_END
#define EEPROM_PHAA_POWERFACTOR_END      (EEPROM_PHAA_POWERFACTOR_START + EEPROM_PHAA_POWERFACTOR_SIZE)
#define EEPROM_PHAB_POWERFACTOR_START    EEPROM_PHAA_POWERFACTOR_END
#define EEPROM_PHAB_POWERFACTOR_END      (EEPROM_PHAB_POWERFACTOR_START + EEPROM_PHAB_POWERFACTOR_SIZE)
#define EEPROM_PHAC_POWERFACTOR_START    EEPROM_PHAB_POWERFACTOR_END
#define EEPROM_PHAC_POWERFACTOR_END      (EEPROM_PHAC_POWERFACTOR_START + EEPROM_PHAC_POWERFACTOR_SIZE)

#define EEPROM_PMEANTLSB_START    EEPROM_PHAC_POWERFACTOR_END
#define EEPROM_PMEANTLSB_END      (EEPROM_PMEANTLSB_START + EEPROM_PMEANTLSB_SIZE)
#define EEPROM_PMEANALSB_START    EEPROM_PMEANTLSB_END
#define EEPROM_PMEANALSB_END      (EEPROM_PMEANALSB_START + EEPROM_PMEANALSB_SIZE)
#define EEPROM_PMEANBLSB_START    EEPROM_PMEANALSB_END
#define EEPROM_PMEANBLSB_END      (EEPROM_PMEANBLSB_START + EEPROM_PMEANBLSB_SIZE)
#define EEPROM_PMEANCLSB_START    EEPROM_PMEANBLSB_END
#define EEPROM_PMEANCLSB_END      (EEPROM_PMEANCLSB_START + EEPROM_PMEANCLSB_SIZE)
#define EEPROM_QMEANTLSB_START    EEPROM_PMEANCLSB_END
#define EEPROM_QMEANTLSB_END      (EEPROM_QMEANTLSB_START + EEPROM_QMEANTLSB_SIZE)
#define EEPROM_QMEANALSB_START    EEPROM_QMEANTLSB_END
#define EEPROM_QMEANALSB_END      (EEPROM_QMEANALSB_START + EEPROM_QMEANALSB_SIZE)
#define EEPROM_QMEANBLSB_START    EEPROM_QMEANALSB_END
#define EEPROM_QMEANBLSB_END      (EEPROM_QMEANBLSB_START + EEPROM_QMEANBLSB_SIZE)
#define EEPROM_QMEANCLSB_START    EEPROM_QMEANBLSB_END
#define EEPROM_QMEANCLSB_END      (EEPROM_QMEANCLSB_START + EEPROM_QMEANCLSB_SIZE)
#define EEPROM_SAMEANTLSB_START    EEPROM_QMEANCLSB_END
#define EEPROM_SAMEANTLSB_END      (EEPROM_SAMEANTLSB_START + EEPROM_SAMEANTLSB_SIZE)
#define EEPROM_SMEANALSB_START    EEPROM_SAMEANTLSB_END
#define EEPROM_SMEANALSB_END      (EEPROM_SMEANALSB_START + EEPROM_SMEANALSB_SIZE)
#define EEPROM_SMEANBLSB_START    EEPROM_SMEANALSB_END
#define EEPROM_SMEANBLSB_END      (EEPROM_SMEANBLSB_START + EEPROM_SMEANBLSB_SIZE)
#define EEPROM_SMEANCLSB_START    EEPROM_SMEANBLSB_END
#define EEPROM_SMEANCLSB_END      (EEPROM_SMEANCLSB_START + EEPROM_SMEANCLSB_SIZE)

//============================================================================================

#define EEPROM_PMEANTF_START    EEPROM_SMEANCLSB_END
#define EEPROM_PMEANTF_END      (EEPROM_PMEANTF_START + EEPROM_PMEANTF_SIZE)
#define EEPROM_PMEANAF_START    EEPROM_PMEANTF_END
#define EEPROM_PMEANAF_END      (EEPROM_PMEANAF_START + EEPROM_PMEANAF_SIZE)
#define EEPROM_PMEANBF_START    EEPROM_PMEANAF_END
#define EEPROM_PMEANBF_END      (EEPROM_PMEANBF_START + EEPROM_PMEANBF_SIZE)
#define EEPROM_PMEANCF_START    EEPROM_PMEANBF_END
#define EEPROM_PMEANCF_END      (EEPROM_PMEANCF_START + EEPROM_PMEANCF_SIZE)
#define EEPROM_PMEANTH_START    EEPROM_PMEANCF_END
#define EEPROM_PMEANTH_END      (EEPROM_PMEANTH_START + EEPROM_PMEANTH_SIZE)
#define EEPROM_PMEANAH_START    EEPROM_PMEANTH_END
#define EEPROM_PMEANAH_END      (EEPROM_PMEANAH_START + EEPROM_PMEANAH_SIZE)
#define EEPROM_PMEANBH_START    EEPROM_PMEANAH_END
#define EEPROM_PMEANBH_END      (EEPROM_PMEANBH_START + EEPROM_PMEANBH_SIZE)
#define EEPROM_PMEANCH_START    EEPROM_PMEANBH_END
#define EEPROM_PMEANCH_END      (EEPROM_PMEANCH_START + EEPROM_PMEANCH_SIZE)
#define EEPROM_IRMSN1_START    EEPROM_PMEANCH_END
#define EEPROM_IRMSN1_END      (EEPROM_IRMSN1_START + EEPROM_IRMSN1_SIZE)
#define EEPROM_URMSA_START    EEPROM_IRMSN1_END
#define EEPROM_URMSA_END      (EEPROM_URMSA_START + EEPROM_URMSA_SIZE)
#define EEPROM_URMSB_START    EEPROM_URMSA_END
#define EEPROM_URMSB_END      (EEPROM_URMSB_START + EEPROM_URMSB_SIZE)
#define EEPROM_URMSC_START    EEPROM_URMSB_END
#define EEPROM_URMSC_END      (EEPROM_URMSC_START + EEPROM_URMSC_SIZE)
#define EEPROM_IRMSN0_START    EEPROM_URMSC_END
#define EEPROM_IRMSN0_END      (EEPROM_IRMSN0_START + EEPROM_IRMSN0_SIZE)
#define EEPROM_IRMSA_START    EEPROM_IRMSN0_END
#define EEPROM_IRMSA_END      (EEPROM_IRMSA_START + EEPROM_IRMSA_SIZE)
#define EEPROM_IRMSB_START    EEPROM_IRMSA_END
#define EEPROM_IRMSB_END      (EEPROM_IRMSB_START + EEPROM_IRMSB_SIZE)
#define EEPROM_IRMSC_START    EEPROM_IRMSB_END
#define EEPROM_IRMSC_END      (EEPROM_IRMSC_START + EEPROM_IRMSC_SIZE)





//============================================================================================
//THD+N, Frequency, Angle and Temperature Registers

#define EEPROM_THDNUA_START    EEPROM_IRMSC_END
#define EEPROM_THDNUA_END      (EEPROM_THDNUA_START + EEPROM_THDNUA_SIZE)
#define EEPROM_THDNUB_START    EEPROM_THDNUA_END
#define EEPROM_THDNUB_END      (EEPROM_THDNUB_START + EEPROM_THDNUB_SIZE)
#define EEPROM_THDNUC_START    EEPROM_THDNUB_END
#define EEPROM_THDNUC_END      (EEPROM_THDNUC_START + EEPROM_THDNUC_SIZE)
#define EEPROM_THDNIA_START    EEPROM_THDNUC_END
#define EEPROM_THDNIA_END      (EEPROM_THDNIA_START + EEPROM_THDNIA_SIZE)
#define EEPROM_THDNIB_START    EEPROM_THDNIA_END
#define EEPROM_THDNIB_END      (EEPROM_THDNIB_START + EEPROM_THDNIB_SIZE)
#define EEPROM_THDNIC_START    EEPROM_THDNIB_END
#define EEPROM_THDNIC_END      (EEPROM_THDNIC_START + EEPROM_THDNIC_SIZE)


#define EEPROM_FREQ_START    EEPROM_THDNIC_END
#define EEPROM_FREQ_END      (EEPROM_FREQ_START + EEPROM_FREQ_SIZE)
#define EEPROM_PANGLEA_START    EEPROM_FREQ_END
#define EEPROM_PANGLEA_END      (EEPROM_PANGLEA_START + EEPROM_PANGLEA_SIZE)
#define EEPROM_PANGLEB_START    EEPROM_PANGLEA_END
#define EEPROM_PANGLEB_END      (EEPROM_PANGLEB_START + EEPROM_PANGLEB_SIZE)
#define EEPROM_PANGLEC_START    EEPROM_PANGLEB_END
#define EEPROM_PANGLEC_END      (EEPROM_PANGLEC_START + EEPROM_PANGLEC_SIZE)
#define EEPROM_TEMP_START    EEPROM_PANGLEC_END
#define EEPROM_TEMP_END      (EEPROM_TEMP_START + EEPROM_TEMP_SIZE)
#define EEPROM_UANGLEA_START    EEPROM_TEMP_END
#define EEPROM_UANGLEA_END      (EEPROM_UANGLEA_START + EEPROM_UANGLEA_SIZE)
#define EEPROM_UANGLEB_START    EEPROM_UANGLEA_END
#define EEPROM_UANGLEB_END      (EEPROM_UANGLEB_START + EEPROM_UANGLEB_SIZE)
#define EEPROM_UANGLEC_START    EEPROM_UANGLEB_END
#define EEPROM_UANGLEC_END      (EEPROM_UANGLEC_START + EEPROM_UANGLEC_SIZE)

#define EEPROM_TEMPERATURE_START    EEPROM_UANGLEC_END+5
#define EEPROM_TEMPERATURE_END     (EEPROM_TEMPERATURE_START + EEPROM_TEMPERATURE_SIZE)
#define EEPROM_TEMPERATURE_F_START    EEPROM_TEMPERATURE_END
#define EEPROM_TEMPERATURE_F_END     (EEPROM_TEMPERATURE_F_START + EEPROM_TEMPERATURE_F_SIZE)
#define EEPROM_HUMIDITY_START    EEPROM_TEMPERATURE_F_END
#define EEPROM_HUMIDITY_END     (EEPROM_HUMIDITY_START + EEPROM_HUMIDITY_SIZE)
#define EEPROM_HEATINDEX_TEMP_START    EEPROM_HUMIDITY_END
#define EEPROM_HEATINDEX_TEMP_END     (EEPROM_HEATINDEX_TEMP_START + EEPROM_HEATINDEX_TEMP_SIZE)
#define EEPROM_HEATINDEX_TEMPF_START    EEPROM_HEATINDEX_TEMP_END
#define EEPROM_HEATINDEX_TEMPF_END     (EEPROM_HEATINDEX_TEMPF_START + EEPROM_HEATINDEX_HUM_SIZE)


//========================================================================================
#define EEPROM_FREQUENCYCAL_START    EEPROM_HEATINDEX_TEMPF_END
#define EEPROM_FREQUENCYCAL_END     (EEPROM_FREQUENCYCAL_START + 6)
#define EEPROM_PGAGAIN_START    EEPROM_FREQUENCYCAL_END
#define EEPROM_PGAGAIN_END     (EEPROM_PGAGAIN_START + 6)
#define EEPROM_VOLTAGEGAIN1_START    EEPROM_PGAGAIN_END
#define EEPROM_VOLTAGEGAIN1_END     (EEPROM_VOLTAGEGAIN1_START + 6)
#define EEPROM_VOLTAGEGAIN2_START    EEPROM_VOLTAGEGAIN1_END
#define EEPROM_VOLTAGEGAIN2_END     (EEPROM_VOLTAGEGAIN2_START + 6)
#define EEPROM_VOLTAGEGAIN3_START    EEPROM_VOLTAGEGAIN2_END
#define EEPROM_VOLTAGEGAIN3_END     (EEPROM_VOLTAGEGAIN3_START + 6)
#define EEPROM_CURRENTGAIN1_START    EEPROM_VOLTAGEGAIN3_END
#define EEPROM_CURRENTGAIN1_END     (EEPROM_CURRENTGAIN1_START + 6)
#define EEPROM_CURRENTGAIN2_START    EEPROM_CURRENTGAIN1_END
#define EEPROM_CURRENTGAIN2_END     (EEPROM_CURRENTGAIN2_START + 6)
#define EEPROM_CURRENTGAIN3_START    EEPROM_CURRENTGAIN2_END
#define EEPROM_CURRENTGAIN3_END     (EEPROM_CURRENTGAIN3_START + 6)
#define EEPROM_CURRENTGAIN_N_START    EEPROM_CURRENTGAIN3_END
#define EEPROM_CURRENTGAIN_N_END     (EEPROM_CURRENTGAIN_N_START + 6)

//========================================================================================
#define EEPROM_CONFIG_STATE_START    EEPROM_CURRENTGAIN_N_END
#define EEPROM_CONFIG_STATE_END     (EEPROM_CONFIG_STATE_START + 1)
#define EEPROM_BOUDRATE_START    EEPROM_CONFIG_STATE_END
#define EEPROM_BOUDRATE_END     (EEPROM_BOUDRATE_START + 4)
#define EEPROM_TCP_PUBLISHINTERVAL_START    EEPROM_BOUDRATE_END
#define EEPROM_TCP_PUBLISHINTERVAL_END     (EEPROM_TCP_PUBLISHINTERVAL_START + 6)
#define EEPROM_MDBUS_BAUDRATE_START    EEPROM_TCP_PUBLISHINTERVAL_END
#define EEPROM_MDBUS_BAUDRATE_END     (EEPROM_MDBUS_BAUDRATE_START + 4)
#define EEPROM_CONFIG_MODE_START    EEPROM_MDBUS_BAUDRATE_END
#define EEPROM_CONFIG_MODE_END     (EEPROM_CONFIG_MODE_START + 32)
#define EEPROM_SERVER_IP_START    EEPROM_CONFIG_MODE_END
#define EEPROM_SERVER_IP_END     (EEPROM_SERVER_IP_START + 10)
#define EEPROM_SERVER_PORT_START    EEPROM_SERVER_IP_END
#define EEPROM_SERVER_PORT_END     (EEPROM_SERVER_PORT_START + 4)
#define EEPROM_HOST_IP_START    EEPROM_SERVER_PORT_END
#define EEPROM_HOST_IP_END     (EEPROM_HOST_IP_START + 10)
#define EEPROM_MDBUS_IP_START    EEPROM_HOST_IP_END
#define EEPROM_MDBUS_IP_END     (EEPROM_MDBUS_IP_START + 10)
#define EEPROM_MODSLAVE_ID_START    EEPROM_MDBUS_IP_END
#define EEPROM_MODSLAVE_ID_END     (EEPROM_MODSLAVE_ID_START + 2)
//========================================================================================

#ifdef SOLAR_METER
#define EEPROM_CAL_SVOLTAGE_START EEPROM_CAL_GAIN_END
#define EEPROM_CAL_SVOLTAGE_END   (EEPROM_CAL_SVOLTAGE_START + EEPROM_CAL_SVOLTAGE_SIZE)
#define EEPROM_CAL_SCT1_START     EEPROM_CAL_SVOLTAGE_END
#define EEPROM_CAL_SCT1_END       (EEPROM_CAL_SCT1_START + EEPROM_CAL_SCT1_SIZE)
#define EEPROM_CAL_SCT2_START     EEPROM_CAL_SCT1_END
#define EEPROM_CAL_SCT2_END       (EEPROM_CAL_SCT2_START + EEPROM_CAL_SCT2_SIZE)
#define EEPROM_CONFIG_END         EEPROM_CAL_SCT2_END
#else
#define EEPROM_CONFIG_END         EEPROM_MODSLAVE_ID_END
#endif

#if EEPROM_CONFIG_END > EEPROM_SIZE
#error EEPROM_SIZE too small
#endif

#define CHECKSUM_SEED 128


// -------------------------------------------------------------------
